//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthersFeatures
{
    using System;
    
    public enum DepartementNames : int
    {
        Physics = 0,
        Chimics = 1,
        Maths = 2,
        Informatique = 3,
        Economics = 4
    }
}
