//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthersFeatures
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollement
    {
        public int EnrollmentID { get; set; }
        public string Grade { get; set; }
        public int StudentStudentID { get; set; }
        public int CourseCourseID { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
