//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OthersFeatures
{
    using System;
    using System.Collections.Generic;
    
    public partial class myView
    {
        public string FisrtName { get; set; }
        public System.DateTime EnrollmentDate { get; set; }
    }
}
